# Generated by Django 6.0.4 on 2026-04-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_schoolclass_class_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolhomework",
            name="grade_importance",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="userclass",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
