# Generated by Django 6.0.4 on 2026-04-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0003_schoolhomework_grade_importance_userclass_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="homework_href",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
