# Generated by Django 6.0.4 on 2026-04-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0010_alter_schoolclass_class_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="homework_href",
            field=models.FileField(blank=True, upload_to=""),
        ),
    ]
