# Generated by Django 6.0.4 on 2026-04-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0011_alter_grade_homework_href"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="grade_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
