# Generated by Django 6.0.4 on 2026-04-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0014_remove_grade_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolclass",
            name="locked",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
