# Generated by Django 6.0.4 on 2026-04-13 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0015_schoolclass_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="homework_number",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="application.schoolhomework",
            ),
        ),
    ]
