# Generated by Django 6.0.3 on 2026-04-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolclass",
            name="class_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
