# Generated by Django 6.0.4 on 2026-04-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0004_grade_homework_href"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userclass",
            name="class_member",
            field=models.ManyToManyField(
                blank=True, null=True, to="application.schoolclass"
            ),
        ),
    ]
