# Generated by Django 6.0.4 on 2026-04-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0005_alter_userclass_class_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="userclass",
            name="user_type",
            field=models.CharField(
                choices=[("Student", "Student"), ("Teacher", "Teacher")],
                default="Student",
                max_length=7,
            ),
        ),
    ]
