# Generated by Django 6.0.4 on 2026-04-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0006_userclass_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userclass",
            name="email",
        ),
        migrations.AddField(
            model_name="userclass",
            name="username",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
