# Generated by Django 6.0.4 on 2026-04-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0007_remove_userclass_email_userclass_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userclass",
            name="name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="userclass",
            name="surname",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
