# Generated by Django 6.0.4 on 2026-04-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0008_alter_userclass_name_alter_userclass_surname"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolhomework",
            name="description",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
