# Generated by Django 6.0.4 on 2026-04-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0009_schoolhomework_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolclass",
            name="class_code",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
