# Generated by Django 6.0.4 on 2026-04-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0012_alter_grade_grade_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolhomework",
            name="upload_after_time",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
