# Generated by Django 6.0.4 on 2026-04-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0013_schoolhomework_upload_after_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grade",
            name="teacher",
        ),
    ]
