# Generated by Django 6.0.4 on 2026-04-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0016_alter_grade_homework_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolhomework",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="schoolhomework",
            name="upload_after_time",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
